"""
Training data for intent classification.
Each intent has example phrases that the model learns to recognize.
"""

INTENT_EXAMPLES = {
    "greeting": [
        "hi",
        "hello",
        "hey",
        "good morning",
        "good evening",
        "hi there",
        "hey there",
        "hii",
        "hiii",
        "hola",
        "namaste",
    ],
    "farewell": [
        "bye",
        "goodbye",
        "see you",
        "thanks bye",
        "thank you bye",
        "see ya",
        "take care",
        "good night",
    ],
    "thanks": [
        "thank you",
        "thanks",
        "thanks a lot",
        "thank you so much",
        "appreciate it",
        "that was helpful",
        "great help",
    ],
    "product_list": [
        "what products do you have",
        "show me all products",
        "what do you sell",
        "list all products",
        "what can I buy",
        "show me everything",
        "what all do you offer",
        "show me your catalog",
        "what items are available",
        "menu",
        "products",
    ],
    "price_query": [
        "what can I buy under 500",
        "products below 1000",
        "anything under 700",
        "show me cheap products",
        "what is the cheapest",
        "budget friendly options",
        "affordable gifts",
        "items under 800",
        "what can I get for 500 rupees",
        "products between 500 and 1000",
        "cheapest product",
        "most expensive product",
        "lowest price",
        "highest price",
        "price range",
    ],
    "product_search": [
        "show me frames",
        "I want a frame",
        "do you have calendars",
        "tell me about the magazine",
        "I need a scrapbook",
        "show me polaroids",
        "do you have action figures",
        "magazine details",
        "I want to buy a hamper",
        "mystery box",
        "what frames do you have",
        "gift for boyfriend",
        "gift for girlfriend",
        "gift for best friend",
        "birthday gift",
        "anniversary gift",
        "valentine gift",
        "gift for her",
        "gift for him",
        "customised gift",
        "personalized gift",
        "memory gift",
        "photo gift",
        "long distance relationship gift",
    ],
    "combo_query": [
        "do you have combos",
        "show me combos",
        "combo deals",
        "combo offers",
        "any bundles",
        "bundle deals",
        "combo packages",
        "what combos are available",
        "combo prices",
        "discounted bundles",
        "save money combo",
        "value pack",
    ],
    "product_info": [
        "tell me more about",
        "what is the hamper",
        "describe the magazine",
        "details about scrapbook",
        "what does the hamper include",
        "magazine specs",
        "how many pages in the magazine",
        "what comes in the mystery box",
        "how many polaroids",
        "frame size",
    ],
    "order_query": [
        "how to order",
        "how can I buy",
        "how to place an order",
        "where to order",
        "how to customize",
        "how do I purchase",
        "ordering process",
        "how to get one",
        "delivery time",
        "how long does it take",
        "shipping",
        "delivery",
    ],
    "contact_query": [
        "how to contact",
        "contact number",
        "phone number",
        "instagram",
        "social media",
        "reach you",
        "get in touch",
        "customer support",
        "whatsapp",
    ],
}

# Responses for non-product intents
STATIC_RESPONSES = {
    "greeting": [
        "Hey there! Welcome to Anchor Customs! I can help you find the perfect customised gift. What are you looking for?",
        "Hi! Welcome to Anchor Customs! Ask me about our products, prices, or combos. How can I help?",
        "Hello! I'm the Anchor Customs assistant. Looking for a personalised gift? I've got you covered!",
    ],
    "farewell": [
        "Bye! Thanks for visiting Anchor Customs. Hope to see you soon!",
        "Goodbye! Feel free to come back anytime. Happy gifting!",
        "See you! Don't forget to check out our combos for great deals!",
    ],
    "thanks": [
        "You're welcome! Let me know if you need anything else.",
        "Happy to help! Feel free to ask more questions anytime.",
        "Glad I could help! Don't hesitate to reach out again.",
    ],
    "order_query": [
        "To order any product, simply DM us on Instagram! Just click 'CUSTOMIZE NOW' on any product or message us directly at @anchor.customs on Instagram. We'll help you personalise your order!",
    ],
    "contact_query": [
        "You can reach us on Instagram at @anchor.customs! Send us a DM and we'll get back to you quickly. That's the best way to place orders and get updates too.",
    ],
}
